### ISSUE TITLE
Hold button behaviour

### ISSUE THREAD

**Issue by Riqueteer** [brynjar-reynisson/GrandStaffMIDIVisualizer#12]
When using the plugin, when hitting Stop in the DAW the notes remain there, as intended.

I think it should **reset when the user hits Play** again in the DAW.

Otherwise, if you want to capture different parts, you have to keep constantly turning the "Hold notes" button on and off.

**Comment by brynjar-reynisson** [comment]
Clearing notes when playback resumes
