### ISSUE TITLE
Stand-alone version

### ISSUE THREAD

**Issue by Riqueteer** [brynjar-reynisson/GrandStaffMIDIVisualizer#13]
In many music video tutorials people use Chordie for showing what they are doing.

It could be interesting to have a **stand-alone version** of the GranStaffMIDIVisualizer, so the same could be done also with this program.

(But of course, this sounds like a whole lot of work :-) ).

**Comment by brynjar-reynisson** [comment]
The installer now includes and installs the standalone executable.
