### ISSUE TITLE
Different behaviour in Octave selector

### ISSUE THREAD

**Issue by Riqueteer** [brynjar-reynisson/GrandStaffMIDIVisualizer#16]
An alternative implementation of the Octave selector would be to have only one button that cycles through the values:
0, 1, 2, 3, -3, -2, -1.

That way the two arrow buttons could be eliminated, having thus more space.

The current width of the octave display (the field that shows the number) could also be reduced.

**Comment by brynjar-reynisson** [comment]
The current idea is to have a knob that looks like this:
![Octaves](https://github.com/user-attachments/assets/f9ad717c-3f39-49b3-938e-ae7cc35fc8e9)
Probably implemented as a custom slider with only seven available values (representing from -3 to 3 octaves).
We'll probably skip the numbers, as they should be intuitively clear by the plugin behaviour.

**Comment by brynjar-reynisson** [comment]
Also re-organized the button layout, now looking like this:
![image](https://github.com/user-attachments/assets/ccea1c1a-4dcb-4880-a575-a88b92a5668c)
