### ISSUE TITLE
Add presets

### ISSUE THREAD

**Issue by Riqueteer** [brynjar-reynisson/GrandStaffMIDIVisualizer#19]
Maybe a good idea to **add presets**, mainly in the stand alone version (in the VST3 version you can set presets directly in the DAW).
I mean just a way of quickly accesing different global configurations.

My suggested implementation would be this:
Add an "S" button for saving and a "L" button for loading.
When clicking them, the user would get a drop down list of numbers, let´s say, 1 to 10, which are the different presets.
Just by clicking the user either saves the current configuration or retrieves a previously saved one.

**Comment by brynjar-reynisson** [comment]
This was almost fully implemented already. The standalone has Options -> Load a saved state and Save current state.
What was missing both in DAW and standalone presets was respecting saved size. That is now fixed.
