### ISSUE TITLE
Improve chord name size in "Only chord" mode

### ISSUE THREAD

**Issue by Riqueteer** [brynjar-reynisson/GrandStaffMIDIVisualizer#7]
Chord name size in the "Only chord" mode is now much smaller.
Some ideas for improving it:
• Make the **chord name always fit the full height** of the plugin (as it was before, I think), so you can really have big letters.
• **Align the chord name to the left** (as it is already the case in all the other modes).

**Comment by brynjar-reynisson** [comment]
The problem with the previous version was that if you have the window really high, but not wide, then chords with long names will only show maybe 2-3 letters of them. We can play around with it and see what formula makes it fit best.

**Comment by brynjar-reynisson** [comment]
Some thoughts about maximizing font size for 'chord only' mode.
The longest strings I found with a short look are 22 characters, e.g. 'Ebaug(M7)(#11,13)(no3)'. It's possible to pre-calculate how wide this string will be with any font height, so we can take a few sample sizes and extrapolate to how wide the string will be with other heights.
I think the goal should be that with any given window width & height, we want to be able to show this max length string as big as possible. I'm still a bit of both minds whether the chord names should be left-aligned or centred. For now, I'll have them left-aligned, but it's easy to change.

**Comment by Riqueteer** [comment]
Hi there Brynjar,

I wouldn´t go that route.
Or, for that case, any other that implies continuosly varying text sizes depending on the length of the chord name, for that would be very unpleasant visually.

I would just keep it as it was before (always maximum height).
Only that, instead on center aligned, left aligned.

This way, yes, chord names could be cut, but it is easy enough to manually resize the window according to the needs.
I think this alternative would be more flexible.

Say, for instance, you know you will play only major and minor chords with 7ths, and you want to keep the display as huge as possible. With this approach you can have the text (C, Cm, CM7, etc) ocuppy the full height of the screen.

Or say you want to have a display as small as possible, and you detect that a chord is cut. Well, it is just a matter of increasing a bit the width manually.

And this makes me think of another possible future feature... presets?

In any case, if you finally try to implement your idea, the longest chord is 25 characters long.
Add one character more, for the chord letter.

**Comment by brynjar-reynisson** [comment]
I don't mean to vary the text height depending on the chord name length, but to always be able to fit in the longest name, and Ebaug(M7)(#11,b13)(no3) includes the root note ;) Maybe 3 more for slash chord?
So, always the same font height for a given window width/height, and always being able to fit the longest string into whatever window size. Shorter strings would just start at the left and not take up all the space on the right.

**Comment by Riqueteer** [comment]
But in that case, the biggest size you could display would be much smaller than the screen height.

With the other alternative (full heigth, left aligned) if the user sees it cuts too much, it is just a matter of reducing the
window height till most or all their chords fit.

**Comment by brynjar-reynisson** [comment]
Hey yeah, sometimes I'm a little thick hehe :) But now I'm thinking that the idea of using the full height, and having the plugin user be responsible for the width is maybe the best idea! So those that play basic chords don't need a wide window, but those who play max-length jazz chords just have to shape their window size so that it will fit in. I'm cautious thinking about presets, cause that would mean different algorithms per preset, and how are we going to allow people to dictate algorithms without some fancy UI? I think it's best to go with the idea of just using the available height, and the user is responsible for having the plugin window wide enough for the chord types that are most common in his/her playing. And left-aligned!

**Comment by Riqueteer** [comment]
Following my proposal (full height chord size, left aligned), it may be a good idea to show a **very faint vertical line indicating the maximum width** (26 characters), so the user can easily resize the window to that maximum if they want to be sure to always see the whole string. This kind of thing:

![imagen](https://github.com/user-attachments/assets/24ff6563-3b2f-440c-8d16-52ae3fd9588e)

Or, maybe it could even be the **maximum possible width**?

**Comment by brynjar-reynisson** [comment]
Going with Diego's idea and using the window height minus button height, and minus button space x 4. Also having buttonspace x 4 on the left and right sides. No need for the faint right line, because we're using almost the full window width on both left and right side.
