### ISSUE TITLE
Bug. Weird behaviour in "Only chord name" mode when pressing "Hold notes"

### ISSUE THREAD

**Issue by Riqueteer** [brynjar-reynisson/GrandStaffMIDIVisualizer#8]
In "Only chord name" mode, when using "Hold notes", the plugin behaves weirdly.
Basically, the chord name stays there all the time, even if you reset the button.
Here you can see how it behaves in all the other modes (right) and in "Only chord name" mode:

![Bug in Only Chord mode](https://github.com/user-attachments/assets/ff70788e-cfd6-43cd-9110-6b3f1fe89650)

**Comment by brynjar-reynisson** [comment]
Closed with a one-liner in main branch.
